admin.album.create:
    path: /admin/album/create
    controller: App\Controller\AlbumController::create

admin.album.edit:
    path: /admin/album/edit/{id}
    controller: App\Controller\AlbumController::edit

admin.album.list:
    path: /admin/album/list/{page}
    controller: App\Controller\AlbumController::listAll
    defaults:
        page: 1
    requirements:
        page: '\d+'

admin.album.delete:
    path: /admin/album/delete/{id}
    controller: App\Controller\AlbumController::delete


front.album.show:
    path: /album/{id}
    controller: App\Controller\AlbumController::showAlbum