# categories routing table

# Admin panel

# create category
admin.categories.create:
  path: /admin/categories/create
  controller: App\Controller\AdminView\CategoriesController::create

# edit category
## view:
admin.categories.edit:
  path: /admin/categories/edit/{id}
  controller: App\Controller\AdminView\CategoriesController::edit

# delete category
## api
admin.categories.delete:
  path: /admin/categories/delete
  controller: App\Controller\CategoriesController::delete

# list categories
## view:
admin.categories.list:
  path: /admin/categories/list/{page}
  controller: App\Controller\AdminView\CategoriesController::listAll
  defaults:
    page: 1
  requirements:
    page: '\d+'

