# categories routing table

# Admin panel

# create category
admin.category.create:
  path: /admin/category/create
  controller: App\Controller\CategoryController::create

# edit category
## view:
admin.category.edit:
  path: /admin/category/edit/{id}
  controller: App\Controller\CategoryController::edit

# delete category
## api
admin.category.delete:
  path: /admin/category/delete/{id}
  controller: App\Controller\CategoryController::delete

# list categories
## view:
admin.category.list:
  path: /admin/category/list/{page}
  controller: App\Controller\CategoryController::listAll
  defaults:
    page: 1
  requirements:
    page: '\d+'

#front.category.show:
#    path: /news/category/{alias}
#    controller: App\Controller\CategoryController::show
front.news.category.activities:
    path: /news/category/activities/{page}
    controller: App\Controller\CategoryController::showActivities
    defaults:
        page: 1
    requirements:
        page: '\d+'
front.news.category.hiring:
    path: /news/category/hiring/{page}
    controller: App\Controller\CategoryController::showHiring
    defaults:
        page: 1
    requirements:
        page: '\d+'
front.news.category.enrollment:
    path: /news/category/enrollment/{page}
    controller: App\Controller\CategoryController::showEnrollment
    defaults:
        page: 1
    requirements:
        page: '\d+'
front.news.category.scholarship:
    path: /news/category/scholarship/{page}
    controller: App\Controller\CategoryController::showScholarship
    defaults:
        page: 1
    requirements:
        page: '\d+'
front.news.category.other:
    path: /news/category/other/{page}
    controller: App\Controller\CategoryController::showOther
    defaults:
        page: 1
    requirements:
        page: '\d+'
