admin.file.get:
  path: /file/{id}
  controller: App\Controller\FileController::getFile

admin.file.upload:
  path: /admin/file/upload
  controller: App\Controller\FileController::upload

admin.file.delete:
  path: /admin/file/delete/{id}
  controller: App\Controller\FileController::delete