# pages routing table

# Admin panel

# create page
## view:
admin.pages.create:
  path: /admin/pages/create
  controller: App\Controller\PagesController::create

# edit page
## view:
admin.pages.edit:
  path: /admin/pages/edit/{id}
  controller: App\Controller\PagesController::edit

# delete page
admin.pages.delete:
  path: /admin/pages/delete/{id}
  controller: App\Controller\PageController::delete

# list page
## view:
admin.pages.list:
  path: /admin/pages/list/{page}
  controller: App\Controller\PagesController:listAll
  defaults:
    page: 1
  requirements:
    page: '\d+'
