# pages routing table

# Admin panel

# create page
## view:
admin.page.create:
  path: /admin/page/create
  controller: App\Controller\PageController::create

# edit page
## view:
admin.page.edit:
  path: /admin/page/edit/{id}
  controller: App\Controller\PageController::edit

# delete page
admin.page.delete:
  path: /admin/page/delete/{id}
  controller: App\Controller\PageController::delete

# list page
## view:
admin.page.list:
  path: /admin/page/list/{page}
  controller: App\Controller\PageController:listAll
  defaults:
    page: 1
  requirements:
    page: '\d+'

front.page.show:
  path: /page/{alias}

front.introduce.history:
    path: /introduce/history
    controller: App\Controller\PageController::showHistory
front.introduce.member:
    path: /introduce/member
    controller: App\Controller\PageController::showMember
front.introduce.honor:
    path: /introduce/honor
    controller: App\Controller\PageController::showHonor
front.introduce.lab:
    path: /introduce/lab/{labname}
    controller: App\Controller\PageController::showLab
    defaults:
        labname: "software-engineering"
front.introduce.future:
    path: /introduce/future
    controller: App\Controller\PageController::showFuture
front.introduce.location:
    path: /introduce/location
    controller: App\Controller\PageController::showLocation

front.network.resource:
    path: /network-resource
    controller: App\Controller\PageController::showNetworkResource

front.contact:
    path: /contact-us
    controller: App\Controller\PageController::showContactUs

front.course.bachelor.attention:
    path: /course/bachelor/attention
    controller: App\Controller\PageController::bachelorCourseAttention
front.course.bachelor.architecture:
    path: /course/bachelor/architecture
    controller: App\Controller\PageController::bachelorCourseArchitecture
front.course.bachelor.graduate.condition:
    path: /course/bachelor/graduate-condition
    controller: App\Controller\PageController::bachelorGraduateCondition
front.course.bachelor.content:
    path: /course/bachelor/content
    controller: App\Controller\PageController::bachelorCourseContent
front.course.bachelor.description:
    path: /course/bachelor/description
    controller: App\Controller\PageController::bachelorCourseDescription

front.course.master.attention:
    path: /course/master/attention
    controller: App\Controller\PageController::masterCourseAttention
front.course.master.architecture:
    path: /course/master/architecture
    controller: App\Controller\PageController::masterCourseArchitecture
front.course.master.graduate.condition:
    path: /course/master/graduate-condition
    controller: App\Controller\PageController::masterGraduateCondition
front.course.master.content:
    path: /course/master/content
    controller: App\Controller\PageController::masterCourseContent
front.course.master.description:
    path: /course/master/description
    controller: App\Controller\PageController::masterCourseDescription