# pages routing table

# Admin panel

# create page
## view:
admin.page.create:
  path: /admin/page/create
  controller: App\Controller\PageController::create

# edit page
## view:
admin.page.edit:
  path: /admin/page/edit/{id}
  controller: App\Controller\PageController::edit

# delete page
admin.page.delete:
  path: /admin/page/delete/{id}
  controller: App\Controller\PageController::delete

# list page
## view:
admin.page.list:
  path: /admin/page/list/{page}
  controller: App\Controller\PageController:listAll
  defaults:
    page: 1
  requirements:
    page: '\d+'

front.page.show:
  path: /page/{alias}

front.introduce.history:
    path: /introduce/history
    controller: App\Controller\PageController::showHistory
front.introduce.member:
    path: /introduce/member
    controller: App\Controller\PageController::showMember
front.introduce.honor:
    path: /introduce/honor
    controller: App\Controller\PageController::showHonor
front.introduce.lab:
    path: /introduce/lab/{labname}
    controller: App\Controller\PageController::showLab
front.introduce.future:
    path: /introduce/future
    controller: App\Controller\PageController::showFuture
front.introduce.location:
    path: /introduce/location
    controller: App\Controller\PageController::showLocation

front.network.resource:
    path: /network-resource
    controller: App\Controller\PageController::showNetworkResource
