# posts routing table

# Admin panel

# create posts
## view:
admin.posts.create:
  path: /admin/posts/create
  controller: App\Controller\PostsController::create

# edit posts
## view:
admin.posts.edit:
  path: /admin/posts/edit/{id}
  controller: App\Controller\PostsController::edit

# delete posts
## api version 1:
admin.posts.delete:
  path: /admin/posts/delete/{id}
  controller: App\Controller\PostsController::delete

# list posts
## view:
admin.posts.list:
  path: /admin/posts/list/{page}
  controller: App\Controller\PostsController::listAll
  defaults:
    page: 1
  requirements:
    page: '\d+'


