public.uploaded.upload:
    path: /public/upload
    controller: App\Controller\PublicUploadController::upload
public.uploaded.delete:
    path: /public/delete/{id}
    controller: App\Controller\PublicUploadController::delete