#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin.index:
    path: /admin
    controller: App\Controller\DefaultController::index

front.index:
    path: /

front.sitemap:
    path: /sitemap.xml