#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin.index:
    path: /admin
    controller: App\Controller\DefaultController::index

front.index:
    path: /
    controller: App\Controller\SiteController::index

front.sitemap:
    path: /sitemap.xml

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

front.news:
    path: /news/{page}
    controller: App\Controller\SiteController::news
    defaults:
        page: 1
    requirements:
        page: '\d+'

front.introduce:
    path: /introduce
    controller: App\Controller\SiteController::introduce

front.course:
    path: /course
    controller: App\Controller\SiteController::course

front.download:
    path: /download
    controller: App\Controller\SiteController::download

front.student.info:
    path: /student-info
    controller: App\Controller\SiteController::studentInfo

front.album:
    path: /album
    controller: App\Controller\SiteController::showAlbums